### ISSUE TITLE
Godex does not compile with float=64

### ISSUE THREAD

**Issue by RicardRC** [GodotECS/godex#254]
It's a new master branch feature.
error given:
```
godex\modules\bullet_physics\overlap_check.cpp(27): error C2664: 'void btConvexShape::project(const btTransform &,const btVector3 &,btScalar &,btScalar &,btVector3 &,btVector3 &) const': cannot convert argument 3 from 'real_t' to 'btScalar &'
godot\thirdparty\bullet\BulletCollision\CollisionShapes\btConvexShape.h(53): note: see declaration of 'btConvexShape::project'
godex\modules\bullet_physics\overlap_check.cpp(758): error C2259: 'overlap_check_polyhedron_polyhedron::NoRes': cannot instantiate abstract class
godex\modules\bullet_physics\overlap_check.cpp(754): note: see declaration of 'overlap_check_polyhedron_polyhedron::NoRes'
godex\modules\bullet_physics\overlap_check.cpp(758): note: due to following members:
godex\modules\bullet_physics\overlap_check.cpp(758): note: 'void btDiscreteCollisionDetectorInterface::Result::addContactPoint(const btVector3 &,const btVector3 &,btScalar)': is abstract
godot\thirdparty\bullet\BulletCollision\NarrowPhaseCollision\btDiscreteCollisionDetectorInterface.h(36): note: see declaration of 'btDiscreteCollisionDetectorInterface::Result::addContactPoint'
systems_base.cpp
```

**Comment by RicardRC** [comment]
maybe btScalar should react to the same flag instead of a custom one?

**Comment by AndreaCatania** [comment]
Yes, bullet should be compiled using double. This should fix the issue.

**Comment by AndreaCatania** [comment]
This should be easily fixable, by adding the proper macro on the bullet module SCsub, in godex. Right now I don't remember the macro name though. I'll check it later.

**Comment by AndreaCatania** [comment]
Yes, I think we just need to append this: https://github.com/godotengine/godot/blob/master/modules/bullet/SCsub#L15-L16

**Comment by RicardRC** [comment]
Still having problems after adding those two lines in godex scons:
```
[Initial build] godex\modules\bullet_physics\overlap_check.cpp(27): error C2664: 'void btConvexShape::project(const btTransform &,const btVector3 &,btScalar &,btScalar &,btVector3 &,btVector3 &) const': cannot convert argument 3 from 'real_t' to 'btScalar &'
[Initial build] godot\thirdparty\bullet\BulletCollision\CollisionShapes\btConvexShape.h(53): note: see declaration of 'btConvexShape::project'Compiling ==> godex\modules\bullet_physics\systems_walk.cpp

systems_base.cpp
godex\modules\bullet_physics\overlap_check.cpp(758): error C2259: 'overlap_check_polyhedron_polyhedron::NoRes': cannot instantiate abstract class
godex\modules\bullet_physics\overlap_check.cpp(754): note: see declaration of 'overlap_check_polyhedron_polyhedron::NoRes'systems_walk.cpp

godex\modules\bullet_physics\overlap_check.cpp(758): note: due to following members:
godex\modules\bullet_physics\overlap_check.cpp(758): note: 'void btDiscreteCollisionDetectorInterface::Result::addContactPoint(const btVector3 &,const btVector3 &,btScalar)': is abstract
godot\thirdparty\bullet\BulletCollision\NarrowPhaseCollision\btDiscreteCollisionDetectorInterface.h(36): note: see declaration of 'btDiscreteCollisionDetectorInterface::Result::addContactPoint'

```

**Comment by RicardRC** [comment]
![imagen](https://user-images.githubusercontent.com/35220750/129475502-14e0dbcb-40ed-4202-9e4f-165fe5df3cf0.png)

It is still not solved.

**Comment by AndreaCatania** [comment]
@RicardRC I've updated godot_godex, and noticed that your PR got merged: https://github.com/GodotECS/godot/commits/godex_version

Please let me know if this is now fixed.

**Comment by RicardRC** [comment]
Yep! Together with the pull request that I just opened, it now compiles.
